"""add profile pic path with bio to users

Revision ID: 320a3866f834
Revises: 07eb82e20ba9
Create Date: 2019-11-28 14:59:43.799202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320a3866f834'
down_revision = '07eb82e20ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###
